on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

name: test-tasks

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-
    - uses: chainguard-dev/actions/setup-kind@main
      with:
        k8s-version: v1.23.x
    - uses: vdemeester/setup-tektoncd@mainx
      with:
        pipeline: v0.40.x
        pipeline-feature-flags: '{"enable-api-fields": "alpha"}'
    - run: |
        kubectl version
        echo "TODO: have a script to run tests :D"
